### ISSUE TITLE
tmp: parameter not set

### ISSUE THREAD

**Issue by ffflorian** [stefanmaric/g#13]
Recently, when running `g self-upgrade` I get the following error:

```
/home/[username]/go/bin/g: 748: /home/[username]/go/bin/g: tmp: parameter not set
```

Content of my `.bashrc`:

```
[...]
export GOPATH="$HOME/go"; export GOROOT="$HOME/.go"; export PATH="$GOPATH/bin:$PATH"; # g-install: do NOT edit, see https://github.com/stefanmaric/g
```

Is there anything I can add to help debugging this?

**Comment by stefanmaric** [comment]
@ffflorian thanks for reporting this issue.

This was a very silly typo. I just pushed a new release with the fix.

You won't be able to upgrade to the fixed version using `g self-upgrade`, so you will need to run the install script once:

```shell
curl -sSL https://git.io/g-install | sh -s
```

Or:

```shell
wget -qO- https://git.io/g-install | sh -s
```

I'm pinning this issue for a while in case anyone else got caught in this situation.

**Comment by ffflorian** [comment]
That was quick, thank you!
