### ISSUE TITLE
git.io no longer resolves 

### ISSUE THREAD

**Issue by rickw** [stefanmaric/g#16]
```
host git.io                                                                               
Host git.io not found: 2(SERVFAIL)
```

**Comment by stefanmaric** [comment]
Hey @rickw , are you still having trouble? git.io resolves without issues for me here in Europe.

githubstatus.com doesn't have recent incidents; what region are you at?

**Comment by rickw** [comment]
@stefanmaric it seems to work now, I guess it was a temporary problem. Thanks.

**Comment by stefanmaric** [comment]
Perfect. Gonna close for now.
