### ISSUE TITLE
Invalid version when install go version < 1.16 on Mac M1 Apple Silicon

### ISSUE THREAD

**Issue by pararang** [stefanmaric/g#27]
**Describe the bug**

Can not install/download Go version below 1.16. i.e: 1.13 and 1.15

**To Reproduce**

1. check all that avail versions using `g list-all`. Version 1.13 and 1.15 exist on the list.
2. execute `g install 1.13`

**Error output**

```
selected: 1.13

ERROR: invalid version 1.13
```

**Environment**

Please give us more info about the system you're getting issues at by running the following commands (copy & paste into your terminal and hit ENTER) and replacing the content here with the output of your terminal:

```shell
echo Architecuture: arm64
echo Full uname: Darwin my-mac.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64
echo Dollar-sign zero expansion: -zsh
echo SHELL: /bin/zsh
echo /etc/shells content:
# List of acceptable shells for chpass(1).
# Ftpd will not allow users to connect who are not using
# one of these shells.
/bin/bash
/bin/csh
/bin/dash
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh

echo go location: /Users/myusername/go/bin/go
go version go1.16 darwin/arm64
echo g location: /Users/myusername/go/bin/g
0.9.0
echo GOROOT: /Users/myusername/.go
echo GOPATH:  /Users/myusername/go
```

**Additional context**

**Comment by stefanmaric** [comment]
Hi @pararang thanks for reporting.

So the deal here is that there are actually no `go` binaries for M1 processors (`arm64`) before `1.16`.

Now, I would expect it should be possible to run pre-`1.16` `amd64` versions of go on M1 on top of Rosetta, but I haven't been able to find info on the matter, I also don't own macs so cannot test myself.

Would you mind to try to install `1.15` using this command:

```shell
g install --arch amd64 1.15.15
```

If the command is successful, mind to also check if your `go` version `1.15.15` actually works in your M1? By running `go` commands like `go version` and `go env`, trying to install some module with `go get` and even maybe compile a project of your own if you have one at hand.

If everything works, we might be able to make `g` use `amd64` for pre-`1.16` versions in M1 by default.

**Comment by pararang** [comment]
Hi @stefanmaric , it seems possible to use amd64 for pre-1.16 versions in M1 by default.

looks like `go` version `1.15.15` works well as my screenshot below.
![Screen Shot 2022-03-18 at 00 17 20](https://user-images.githubusercontent.com/8720184/158846241-ce6ac74c-ccb2-404a-a910-17e9afc63b3a.jpg)

I also tried `g install --arch amd64 1.13`, it works.
![Screen Shot 2022-03-18 at 00 19 00](https://user-images.githubusercontent.com/8720184/158846618-dd7dbdd6-62dc-432a-b051-d85c24947945.jpg)

Hopefully, it helps you to verify and found the solution for the issue.

**Comment by juev** [comment]
Hello,

today I was try install go 1.18.1 with g:
```bash
 10:13:29  ❯ g install latest

      selected: 1.18.1

  ERROR: invalid version 1.18.1
```

```bash
~
 10:13:55  ❯ g install --arch amd64 latest

      selected: 1.18.1

  ERROR: invalid version 1.18.1
```

I use Mac M1 Apple Silicon.

```bash
~
 10:15:33  ❯ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/deevsyukov/Library/Caches/go-build"
GOENV="/Users/deevsyukov/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/deevsyukov/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/deevsyukov/go"
GOPRIVATE=""
GOPROXY=""
GOROOT="/Users/deevsyukov/.go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/Users/deevsyukov/.go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bx/pg29yphj0fj6g1p8zybrh17c0000gq/T/go-build410784229=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by juev** [comment]
As I can see, we don't have darwin package in this time:
https://go.dev/dl/

<img width="1003" alt="Снимок экрана 2022-04-13 в 12 46 02" src="https://user-images.githubusercontent.com/114635/163149849-a225bb29-3d5a-41e8-918a-b672fb349c0b.png">

Only windows and linux/freebsd is present.

But g talked what 1.18.1 for darwin is exist.

**Comment by stefanmaric** [comment]
@juev it seems someone went wrong with the build of that release: https://github.com/golang/go/issues/52317

I would suggest to wait a little bit until the golang team publishes the build.

If you desperately need the point 1 patch release because of security reasons, I would suggest compiling the binaries in a diff machine, like your CI environment, a remote server, etc.

Otherwise, I would personally just stick to 1.18.0 until .1 is published.

**Comment by juev** [comment]
Got it, thank you!
