### ISSUE TITLE
add website link to CLI help

### ISSUE THREAD

**Issue by brendensoares** [stefanmaric/g#28]
`g` is such a vague command name and there is no way to find out what the tool is, even when running `g --help`. Please add the repo URL and possibly a description.

**Comment by stefanmaric** [comment]
Hi @brendensoares good suggestion! PRs are welcomed.

**Comment by pararang** [comment]
hi @brendensoares @stefanmaric. I do like to make a PR for this issue. Is the description below is enough?
```console
  g git:(add-description-on-help) ✗ ./bin/g --help

  [https://github.com/stefanmaric/g]

  A simple go version manager, gluten-free.

  Usage: g [COMMAND] [options] [args]

  Commands:
  ...
```
