### ISSUE TITLE
ERROR: invalid version

### ISSUE THREAD

**Issue by CyshallChan** [stefanmaric/g#33]
**Describe the bug**

ERROR: invalid version

**To Reproduce**

g install latest

**Error output**

```shell
ERROR: invalid version
```

**Environment**

Please give us more info about the system you're getting issues at by running the following commands (copy & paste into your terminal and hit ENTER) and replacing the content here with the output of your terminal:

echo Architecuture: x86_64
echo Full uname: Linux Cyshall-Desktop 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
echo Dollar-sign zero expansion: "/usr/bin/zsh"
echo SHELL: "/usr/bin/zsh"
echo /etc/shells content:
```shell
/bin/sh
/bin/bash
/usr/bin/bash
/bin/rbash
/usr/bin/rbash
/usr/bin/sh
/bin/dash
/usr/bin/dash
/usr/bin/tmux
/usr/bin/screen
/bin/zsh
/usr/bin/zsh
```
echo go location: go version go1.20 linux/amd64
echo g location: /root/.go/bin/g &&  0.9.1
echo GOROOT: "/root/.g/goT"
echo GOPATH:  "/root/.go"
```

**Additional context**

Add any other context about the problem here.

**Comment by stefanmaric** [comment]
@CyshallChan can you share the full output of running `g install latest`?

**Comment by CyshallChan** [comment]
the full output is just `ERROR: invalid version`. 
just tried reinstalling wsl2 and now the problem is solved🤣
