### ISSUE TITLE
GOPATH default value is wrong 

### ISSUE THREAD

**Issue by AuHau** [stefanmaric/g#5]
Even though README says that default values are:

> GOROOT: $HOME/.go
> GOPATH: $HOME/go

Upon `g` installation, the `GOPATH` variable in my `config.fish` is set to `$HOME/.go`, which then mess up everything, because upon installation of any version the `g` binary is removed. Not sure if it is only Fish specific or affects also other shells.

When I have corrected manually this error, everything worked as expected.

**Comment by AuHau** [comment]
Hmmmm, checked your `g` script and it seems correct. It might be a problem on my system, investigating a bit more. Will let you know.

**Comment by AuHau** [comment]
Hmmm, yeah problem was on my end. The `GOPATH` variable was set as a universal variable in fish and hence persisted even when I have removed the original export command. From now on, I am avoiding universal variables 😆

**Comment by stefanmaric** [comment]
Hey @AuHau. Good you solved it!

I think I will add some more info on the install script to let the user know whenever the defaults locations are being used or not.

Thanks for sharing your experience.
