### ISSUE TITLE
Can't install versions <1.5 on macOS

### ISSUE THREAD

**Issue by RobertYost** [stefanmaric/g#7]
Whenever I try installing any version of Go lower than 1.5, I get the following error:

```
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

I believe this is because the script tries downloading from https://dl.google.com/go/go1.4.darwin-amd64.tar.gz, but if you go to https://golang.org/dl/ , there are no such links that follow the format that the script expects. It seems as if they only started following that format with 1.5 and later.

**Comment by stefanmaric** [comment]
Hi @RobertYost , thanks from bringing this up!

>  there are no such links that follow the format that the script expects. It seems as if they only started following that format with 1.5 and later.

Interesting, I didn't notice.

I will take and look at see if the `10.8` builds actually work on newer macos versions.

This would require to put some handlers to check whenever the running macos is bellow or above 10.8.

I'm open to PRs, otherwise I will probably have a fix by end of week.

**Comment by stefanmaric** [comment]
Hey @RobertYost,

I was looking into this but cannot actually test properly since I would require a Mac with macos `10.11` or lower.

On what version of macos are you trying to install go `1.4`?

For reference, here a compat table: https://github.com/golang/go/wiki/Darwin

**Comment by RobertYost** [comment]
> Hey @RobertYost,
> 
> I was looking into this but cannot actually test properly since I would require a Mac with macos `10.11` or lower.
> 
> On what version of macos are you trying to install go `1.4`?
> 
> For reference, here a compat table: https://github.com/golang/go/wiki/Darwin

Ah that would make sense why I couldn't get go <=1.4 to work on my machine by installing manually, I am using a macbook w/ kernel version 17.7.0, so High Sierra. I tried searching for a compat table but couldn't find one, thanks for that.

**Comment by stefanmaric** [comment]
> I couldn't get go <=1.4 to work on my machine by installing manually, I am using a macbook w/ kernel version 17.7.0, so High Sierra.

In that case I will skip this feature for now, until more people demand it, since it would only benefit a very small, ever-shrinking niche.

> I tried searching for a compat table but couldn't find one, thanks for that.

You're welcome! :heart: 

Closing this but feel free to re-open and/or continue the discussion.
